USE [master]
GO
IF NOT EXISTS (SELECT name FROM sys.syslogins WHERE name = '__LOGIN_OR_USER__')
	BEGIN
	CREATE LOGIN [__LOGIN_OR_USER__] FROM WINDOWS WITH DEFAULT_DATABASE=[tempdb]
	END
GO
USE [__DB_NAME__]
GO
IF NOT EXISTS (SELECT name FROM sys.sysusers WHERE name ='__LOGIN_OR_USER__')
	BEGIN
	CREATE USER [__LOGIN_OR_USER__] FOR LOGIN [__LOGIN_OR_USER__]
	ALTER ROLE [db_webapp] ADD MEMBER [__LOGIN_OR_USER__]
	END
GO